### PR TITLE
Update chromedriver service and instructions to match latest Drupal 11 latest

### PR DESCRIPTION
**Pull request by scotteuser**
Thanks for this very helpful chromedriver docker compose and detailed instructions, has been very helpful as a reference!

## The New Solution/Problem/Issue/Bug:

- The default sample chromedriver docker compose file has some issues:
  - The mysql connection sample does not work as is
  - chromeOptions is deprecated and should be goog:chromeOptions
  - adding version is deprecated
- The README is missing some instructions
  - It specifies only leaving the mink args unchanged, but actually the sample docker compose provides more values than that

## How this PR Solves The Problem:

- Updates docker compose file to fix the above
- Updates the README to fix the above

### CODE REVIEW

**Comment by scotteuser** [comment]
I think this is for @heddn and @mglaman as the contributors of this portion of the ddev contrib as per the readme list of contributors https://github.com/ddev/ddev-contrib/blob/master/docker-compose-services/drupalci-chromedriver/README.md

Thank you!

**Comment by rfay** [comment]
I don't mind pulling this, but I don't think anybody uses this any more. Instead, they use the well-maintained https://github.com/ddev/ddev-selenium-standalone-chrome - see instructions there.

**Comment by scotteuser** [comment]
Oh I see! Should I update the README to make that more clear? At the moment it seems to indicate it just as an alternative rather than the preferred way, and though it appeared before the Apple M1 comment I thought it was intended to be for those on such devices.

Or could be removed altogether/marked as deprecated? If it is sticking around makes sense to keep it up to date with latest Drupal I guess though (as is it doesn't work as per the issue description).

Thanks!
Scott

**Comment by rfay** [comment]
Yes, please update the README. I think everybody in the Drupal world is using that add-on. And probably we should be saying "Apple Silicon" instead of "M1" these days. You can update this with another commit or do another PR. Thanks for taking care of this! Mostly ddev-contrib has been replaced with better-maintained add-ons.

**Review by rfay — APPROVED** [review]
Thanks!

**Comment by scotteuser** [comment]
Thanks!

**Pull request merged**
